name: socketcan

on:
  push:
  pull_request:

jobs:
  test:
#    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - preset: "linux-test-qemu"
            target: "can_core_test"

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Install toolchain
      run: sudo apt update && DEBIAN_FRONTEND=noninteractive sudo apt-get install -y sshpass screen cmake build-essential python3 git gcovr ninja-build
    - name: Configure
      run: cmake -B build . --preset ${{ matrix.preset }}
    - name: Build
      run: cmake --build build --parallel $(nproc) -t ${{ matrix.target }}
    - name: "vm: install toolchain"
      run: sudo apt-get install git gnupg2 linux-virtual libguestfs-tools -y --no-install-recommends
    - name: "vm: checkout sil kit"
      run: |
        mkdir build/sil-kit
        cd build-sil-kit
        git clone https://github.com/vectorgrp/sil-kit-adapters-qemu .
        git checkout ${SIL_KIT_QEMU_COMMIT}
    - name: "vm: build vm image"
      run: |
        cd build/sil-kit
        ./tools/build-silkit-qemu-demos-guest.sh
    - name: "vm: run tests"
      run: |
        cd build/sil-kit
        ./tools/run-silkit-qemu-demos-guest.sh &
        ./waitforssh.sh localhost -p10022
        sshpass -proot ssh -q -p10022 -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null root@localhost -p root -t "mkdir -p /work"
        sshpass -proot scp -P10022 -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null $(pwd)/build/${{ matrix.target }}/test-bin/${{ matrix.target }} root@localhost:/work/test
        sshpass -proot ssh -q -p10022 -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null root@localhost -p root -t "cd /work && ./test"
        sshpass -proot ssh -q -p10022 -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null root@localhost -q -t "shutdown 00"
#    - name: Test
#      run: GTEST_OUTPUT="xml:$(pwd)/test_detail.xml" cmake --build build -t ${{ matrix.target }}_coverage
#    - name: Report test summary
#      uses: test-summary/action@v2
#      with:
#        paths: "test_detail.xml"
#      if: always()